### ISSUE TITLE
Please create accounts for Rizky, Etienne and Ismail on geonode and geocode-staging kV's

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe-infrastructure#20]
@hvisage can you please up accounts with sudo rights for Etienne, Rizky and Ismail on the two above mentioned kvm's?

**Comment by hvisage** [comment]
O_o
Users already created (via ansible)

**Comment by hvisage** [comment]
And they are already part of the sudo group...

`sudo:x:27:gavin,hvisage,richard,tim,christian,etienne,maria,rizky,timlinux,realtime
`
PS: Need to get merges for the development branch to get back in sync again

**Comment by ismailsunni** [comment]
hi @hvisage 
I tried to login, but it asked me a password. Do you have any idea why?

I have checked my pub key, and it's the same one with the one that I have in my laptop.

**Comment by timlinux** [comment]
@hvisage looking at `/etc/password` I don't see a login for him:

```
sshd:x:104:65534::/var/run/sshd:/usr/sbin/nologin
gavin:x:1001:1001::/home/gavin:/bin/bash
hvisage:x:1002:1002::/home/hvisage:/bin/bash
richard:x:1003:1003::/home/richard:/bin/bash
tim:x:1004:1004::/home/tim:/bin/bash
christian:x:1005:1005::/home/christian:/bin/bash
etienne:x:1006:1006::/home/etienne:/bin/bash
maria:x:1007:1007::/home/maria:/bin/bash
rizky:x:1008:1008::/home/rizky:/bin/bash
timlinux:x:1009:1009::/home/timlinux:/bin/bash
realtime:x:1010:1010::/home/realtime:/bin/bash
tomcat7:x:106:114::/usr/share/tomcat7:/bin/false
postgres:x:105:113:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
```

**Comment by timlinux** [comment]
(I meant for user: ismail above)

**Comment by hvisage** [comment]
Ah! Sorry I missed Ismail :(
On a plane and on the road till this evening, will attend then as I check
the Ansible again I need to get pulled in.

**Comment by hvisage** [comment]
Please check again
Rizky, I have two pub keys for you, I’ve added both to all

---

Hendrik Visage
Envisage Systems / Envisage Cloud Solutions
084-612-5345 or 083-675-5506
hvisage@envisage.co.za mailto:hvisage@envisage.co.za

**Comment by ismailsunni** [comment]
Work for me. Thanks @hvisage

**Comment by timlinux** [comment]
Thanks @hvisage
